### ISSUE TITLE
Using CDQR Docker instead of cdqr.py

### ISSUE THREAD

**Issue by orlikoski** [orlikoski/Skadi#100]
Make some sort of alias or script that enables the use of the CDQR docker but uses the same cdqr commands as older versions of Skadi

The final solution should include options for Windows, Linux, and MacOS

**Comment by lkuik** [comment]
Bulk of the work is done, need to update documentation and make final tweaks then once ready push to master

**Comment by orlikoski** [comment]
These changes have been merged to master. Closing

New helper script to make using CDQR docker easier details are here https://github.com/orlikoski/CDQR/tree/master/Docker
