### ISSUE TITLE
Configuring static ip address in the Skadi VM

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/Skadi#123]
Hello,

I wanted to configure a static ip address for the ELK stack. 
or the entire Skadi VM. how should I proceed?

Thanks and Regards
Tej Gandhi

**Comment by lkuik** [comment]
Hi @tej7gandhi 
For the Skadi VM itself, you can set this in networking options under virtualbox, or vmware whatever product you are using for the virtual machine.

Just keep in mind, if you want to access the Skadi portal hosted on the Skadi VM from your physical host, you will need to set up the networking properly in VmWare or Virtualbox to allow access from the host.  So for example setting the network adapter settings to Bridged mode
