### ISSUE TITLE
Issues with cloning

### ISSUE THREAD

**Issue by Adriikas** [orlikoski/Skadi#124]
I have installed docker and tested but receiving the following error when installing Skadi = `wget -O /tmp/buildskadi.sh https://raw.githubusercontent.com/orlikoski/skadi/master/scripts/buildskadi.sh`
The following ports are open: 80,5432,9200.

Building dependency tree       
Reading state information... Done
vm.max_map_count = 262144
vm.max_map_count=262144
Renaming Host to skadi
Enabling UFW firewall to only allow OpenSSH and Ngninx Full
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup
Downloading Skadi
Cloning into '/opt/Skadi'...
fatal: Remote branch master not found in upstream origin

**Comment by orlikoski** [comment]
That's a problem due to me renaming Master to Main. I recommend using the pre-built VM or the docker native version until it is fixed. 

Does anyone want to take a shot at fixing it?

**Comment by orlikoski** [comment]
I updated the instances of branch master to main that I found in Skadi/scripts and that should take care of the issue. Please let us know if it doesn't

**Comment by lkuik** [comment]
hey @Adriikas just following up on @orlikoski  comment above, has the issue been resolved since the changes were made to Skadi/script?

Thanks

**Comment by lkuik** [comment]
Documentation has been updated, tested and verified working. 
Closing issue
