### ISSUE TITLE
Feature Request - Display IP on VM login screen

### ISSUE THREAD

**Issue by ecapuano** [orlikoski/Skadi#67]
Microscopic feature request to speed up usage - since Skadi can be used immediately after deployment by aiming CyLR at it, if the VM displayed it's `ens33` IP address on the logon screen, a responder could more quickly begin firing data at it without logging in solely to to run `ipconfig`.

One issue that could interfere is Ubuntu's dynamic naming of the network interfaces... It may always be `ens33`, but it could change if someone were to alter the interface type assigned to the VM.

Feel free to ignore, just a minor suggestion on an overall fantastic tool.

Reference: https://askubuntu.com/a/217519

**Comment by orlikoski** [comment]
Interesting concept for sure and thanks for bringing it up. I think the challenging part comes in chosing the correct interface to pull the IP address from. VMWare likes to use `ens33` while VirtualBox likes another name. It would also be challenging to pull off for those using the signed installation script as that can be run on any box with any number of interface names.

**Comment by ecapuano** [comment]
Ah, yes, all good points... This is a fairly insignificant feature and likely not worth having to solve all of those challenges. Feel free to close :)
