### ISSUE TITLE
Kibana: Mactime search GUI

### ISSUE THREAD

**Issue by garanews** [orlikoski/Skadi#73]
It would be useful to have something like this:
http://christophe.vandeplas.com/2014/06/mactime-magic-with-elk.html

**Comment by orlikoski** [comment]
I agree that is a good looking dashboard and if anyone is interested in putting one together to include in the base VM contact me

**Comment by lkuik** [comment]
Looked into this, tried to import the mactime.json and it isn't compatible with ELK 6.5.1
