### ISSUE TITLE
Create Automation Handler on CCF-VM server

### ISSUE THREAD

**Issue by orlikoski** [orlikoski/Skadi#8]
Create a script/process that accepts data from automation tools to perform functions on the server.

Ensure it is secure and cannot be misused by bad actors.
Ensure it can be used by the cloud version.

Such as (but not limited to):

- Process data
- System for user to initial Start/Stop/Restart services/components on-demand
- Data management (move things around on disk or in the DB like purge timesketches)

**Comment by rough007** [comment]
this is being developed in the "automation" branch

**Comment by orlikoski** [comment]
This has been completed and merged to Master
