### ISSUE TITLE
Update Secure Networking Add-on pack

### ISSUE THREAD

**Issue by orlikoski** [orlikoski/Skadi#88]
The Secure Networking Add-On pack no longer works with v2019.1.

Update the Secure Networking pack to support the Nginx Docker container.  Probably going to involve https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/

**Comment by orlikoski** [comment]
This should try to use mkcert as part of the solution.  The solution should be a script that installs mkcert and then updates the nginx config accordingly.

This script should work for default builds as well as custom installs

**Comment by lkuik** [comment]
All TLS changes to enable encryption for SkadiVM have been deployed to master.
Can use mkcert or Letsencrypt
Closing issue out
