### ISSUE TITLE
Make ES Heap Size ENV Var

### ISSUE THREAD

**Issue by orlikoski** [orlikoski/Skadi#96]
`- "ES_JAVA_OPTS=-Xms${HEAP_SIZE} -Xmx${HEAP_SIZE}"`

and then put `HEAP_SIZE=1g` in /opt/Skadi/Docker/.env

**Comment by boingomw** [comment]
Hi,
The raw file is updated, but the one in the buildskadi.tgz doesn't have the HEAP variable yet, which causes the build to fail.  Confirmed that if that variable is manually added before the script is run, the entire install works.

**Comment by orlikoski** [comment]
Thank you for bringing this up and the latest version has this fixed
